// This will hold all the Button texts
export const BUTTON_TEXT = Object.freeze({
  retry: 'Retry',
  home: 'Home',
  addProject: 'Add project',
  toggleTheme: 'Toggle theme',
  submit: 'Submit',
  continueWithGitHub: 'Continue with Github',
  continueWithGoogle: 'Continue with Google',
  copy: 'Copy',
  singUp: 'Sign Up',
  exploreProjects: 'Explore projects',
  editProfile: 'Edit profile',
  gitHub: 'GitHub',
  linkedIn: 'LinkedIn',
  twitter: 'Twitter',
  website: 'Website',
  saveChanges: 'Save changes',
  live: 'Live',
  edit: 'Edit',
  stats: 'Stats',
  contribute: 'Contribute',
  share: 'Share',
  goHome: 'Go Home',
});
