name: chore
description: Report an issue that doesn't effect on production code.
title: '[CHORE] <description>'
labels: ['chore']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the improvement / feature suggestion
    validations:
      required: true
