name: General Feature Request
description: Have a new idea/feature for this project? Please suggest!
title: '[FEATURE] <description>'
labels: ['feature']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the enhancement you propose.
    validations:
      required: true
